name: BukkitConsumableStorage
main: me.Jonnyfant.BukkitConsumableStorage.BukkitConsumableStorage
author: Jonnyfant
version: 1.1
commands:
  storetotem:
    usage: /<command>
    permission: totemstorage.use
permissions:
  totemstorage.use:
    default: true

